export { default as SimpleLogin } from "./Login"
export { default as SimpleRegister } from "./Register"

export { default as SimpleMain } from "./Simple"
export { default as SimpleNavbar } from "./Navbar"
export { default as SimpleAddUser } from "./AddUser"
export { default as SimpleUserOpen } from "./Open"
export { default as SimpleHome } from "./pages/Home"
export { default as SimpleUsers } from "./pages/Users"
export { default as SimpleSale } from "./pages/Sale"
export { default as SimpleMeeting } from "./pages/Meeting"
export { default as SimpleMissed } from "./pages/MissedCall"
export { default as SimpleRejected } from "./pages/Rejected"